### ISSUE TITLE
Nestable widget property nameAttribute probably not used

### ISSUE THREAD

**Issue by ComradePashka** [voskobovich/yii2-tree-manager#1]
When nameAttribute defined as config parameter, formFieldsCallable is missed (null) and there is no field 'name' in the model, e.g.:

```
Nestable::widget([
    'modelClass' => 'common\models\Post',
    'nameAttribute' => 'label'
])
```

then code run to line:
https://github.com/voskobovich/yii2-tree-manager/blob/master/widgets/nestable/Nestable.php#L117
where string constant hardcoded and is causing unfixable error. so the only one possibility to use nameAttribute - is to have required mandatory field 'name'. just ignore it and use another field as needed

**Comment by voskobovich** [comment]
Hmm. Sorry that I have not seen this.
I do not understand what the problem. You can't change the field name `name` to `label`?
