### ISSUE TITLE
Не получается сделать дерево больше 5 уровней

### ISSUE THREAD

**Issue by martrix78** [voskobovich/yii2-tree-manager#10]
вижу что запрос уходит, но элемент возвращается на тот же уровень

**Comment by voskobovich** [comment]
@martrix78 Я не сталкивался с подобной проблемой. Возможности протестировать сейчас нет (т.к. нет ни одного проект под рукой где бы я мог воссоздать песочницу). Вы можете найти причину на своем текущем проекте, описать проблему и мы вместе найдем решение :)
