### ISSUE TITLE
getAttributes and virtual attribute

### ISSUE THREAD

**Issue by ztdan4ik** [voskobovich/yii2-tree-manager#11]
Hi there!
Thanks for you great job!

I have one suggesting for your widget here https://github.com/voskobovich/yii2-tree-manager/blob/master/src/widgets/nestable/Nestable.php#L146

Can you use `$node->{$this->nameAttribute}` insted of `$node->getAttribute($this->nameAttribute)`
It will give ability to use model virtual attributes. I thing it will be more flexible.

Thanks!

**Comment by voskobovich** [comment]
What do you mean by a virtual attribute? Give an example.

**Comment by ztdan4ik** [comment]
As you know, in Yii2 active record model has attributes from table what is belong to this model and could be getted buy getAttribute method.
But some time we need virtual attributes in model class which is not part of table and active record as well.

For example:

```
<?php

class User extend ActiveRecord {

	private $_fullname; //this is virtual attribute

	/**
	* Getter
	*/
	public function getFullname()
	{
		// last_name and name part of user model/table - this is real attributes.
		return $this->last_name.' '.$this->name;
	}

	/**
	* Setter
	*/
	public function setFullName($value)
	{
		$this->_fullname = $value;
	}

}
```

In my case I have multilang categories and behavior which creating virtual attribute for model with category name on current language from related table. 

Here you can read more about this concept 
https://www.yiiframework.com/doc/guide/2.0/en/concept-properties
https://www.yiiframework.com/wiki/167/understanding-virtual-attributes-and-getset-methods
Here is behavior what Im using for getting category name in current language https://github.com/2amigos/yii2-translateable-behavior

**Comment by voskobovich** [comment]
I understood you. Create a pull request with changes and I will accept it.

**Comment by ztdan4ik** [comment]
#12 Done

**Comment by ztdan4ik** [comment]
Any news?

**Comment by voskobovich** [comment]
@ztdan4ik Merged!
