### ISSUE TITLE
Yii Bootstrap 2.1

### ISSUE THREAD

**Issue by loveorigami** [voskobovich/yii2-tree-manager#3]
Не могу обновить в проекте yii-bootstrap до версии 2,1.
Использую этот виджет, но в нем указана версия bootstrap 2,0
https://github.com/voskobovich/yii2-tree-manager/blob/master/composer.json#L28

**Comment by voskobovich** [comment]
На сколько я помню, то в этом виджете ничего не привязано к версии бутстрапа и ее смело можно обновлять. Можно еще текст ошибки которую выдает композер?

**Comment by loveorigami** [comment]
У тебя в композере задана версия 2.0.
Если я у себя в комозере ставлю 2.1, мой composer.json конфликтует с твоим, указывая на то, что должен стоять bootstrap 2.0, т.к. этого требует твой composer.json.

тут
https://github.com/voskobovich/yii2-tree-manager/blob/master/composer.json#L28

можно указать >=2.0

**Comment by voskobovich** [comment]
Попробуй поставить @dev и затестить.
Я поставил `^2.0.0` это эквивалетно как `>=2.0.0 <3.0.0`.

**Comment by lvbaocheng** [comment]
I also encountered the same problem.I can't update the yii-bootstrap project to version 2.1.How to solve?
